### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by kingjr** [kingjr/aws#1]
- [x] install
- [x] auto update
- [x] set environment variable
- [ ] separate pip, bash variables etc to call them at install or update
- [ ] sync notebooks with dropbox
- [ ] separate upgrade and quick update
- [ ] check that server isn't running already
- [ ] start server at launch
- [ ] protected data versus results
- [ ] cuda
- [ ] mkl
- [ ] add subnets
- [ ] add github credentials for private reps
